
package webService.client;

import java.util.ArrayList;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransitoWeb", targetNamespace = "http://webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransitoWeb {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "connectVia", targetNamespace = "http://webService/", className = "webService.client.ConnectVia")
    @ResponseWrapper(localName = "connectViaResponse", targetNamespace = "http://webService/", className = "webService.client.ConnectViaResponse")
    @Action(input = "http://webService/TransitoWeb/connectViaRequest", output = "http://webService/TransitoWeb/connectViaResponse")
    public void connectVia(
        @WebParam(name = "arg0", targetNamespace = "")
        Via arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CanOpen")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CanOpen", targetNamespace = "http://webService/", className = "webService.client.CanOpen")
    @ResponseWrapper(localName = "CanOpenResponse", targetNamespace = "http://webService/", className = "webService.client.CanOpenResponse")
    @Action(input = "http://webService/TransitoWeb/CanOpenRequest", output = "http://webService/TransitoWeb/CanOpenResponse")
    public boolean canOpen(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "connectSemaforo", targetNamespace = "http://webService/", className = "webService.client.ConnectSemaforo")
    @ResponseWrapper(localName = "connectSemaforoResponse", targetNamespace = "http://webService/", className = "webService.client.ConnectSemaforoResponse")
    @Action(input = "http://webService/TransitoWeb/connectSemaforoRequest", output = "http://webService/TransitoWeb/connectSemaforoResponse")
    public void connectSemaforo(
        @WebParam(name = "arg0", targetNamespace = "")
        Semaforo arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webService.client.Veiculo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSortedVeiculos", targetNamespace = "http://webService/", className = "webService.client.GetSortedVeiculos")
    @ResponseWrapper(localName = "getSortedVeiculosResponse", targetNamespace = "http://webService/", className = "webService.client.GetSortedVeiculosResponse")
    @Action(input = "http://webService/TransitoWeb/getSortedVeiculosRequest", output = "http://webService/TransitoWeb/getSortedVeiculosResponse")
    public ArrayList<Models.Veiculo> getSortedVeiculos();

}
