
package webService.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VeiculoWebService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8080/veiculo?wsdl")
public class VeiculoWebService
    extends Service
{

    private final static URL VEICULOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException VEICULOWEBSERVICE_EXCEPTION;
    private final static QName VEICULOWEBSERVICE_QNAME = new QName("http://webService/", "VeiculoWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/veiculo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEICULOWEBSERVICE_WSDL_LOCATION = url;
        VEICULOWEBSERVICE_EXCEPTION = e;
    }

    public VeiculoWebService() {
        super(__getWsdlLocation(), VEICULOWEBSERVICE_QNAME);
    }

    public VeiculoWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEICULOWEBSERVICE_QNAME, features);
    }

    public VeiculoWebService(URL wsdlLocation) {
        super(wsdlLocation, VEICULOWEBSERVICE_QNAME);
    }

    public VeiculoWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEICULOWEBSERVICE_QNAME, features);
    }

    public VeiculoWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VeiculoWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VeiculoWeb
     */
    @WebEndpoint(name = "VeiculoWebPort")
    public VeiculoWeb getVeiculoWebPort() {
        return super.getPort(new QName("http://webService/", "VeiculoWebPort"), VeiculoWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VeiculoWeb
     */
    @WebEndpoint(name = "VeiculoWebPort")
    public VeiculoWeb getVeiculoWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "VeiculoWebPort"), VeiculoWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEICULOWEBSERVICE_EXCEPTION!= null) {
            throw VEICULOWEBSERVICE_EXCEPTION;
        }
        return VEICULOWEBSERVICE_WSDL_LOCATION;
    }

}
