
package webService.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TransitoWebService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8080/transito?wsdl")
public class TransitoWebService
    extends Service
{

    private final static URL TRANSITOWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webService.cliente.TransitoWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webService.cliente.TransitoWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/transito?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/transito?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TRANSITOWEBSERVICE_WSDL_LOCATION = url;
    }

    public TransitoWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransitoWebService() {
        super(TRANSITOWEBSERVICE_WSDL_LOCATION, new QName("http://webService/", "TransitoWebService"));
    }

    /**
     * 
     * @return
     *     returns TransitoWeb
     */
    @WebEndpoint(name = "TransitoWebPort")
    public TransitoWeb getTransitoWebPort() {
        return super.getPort(new QName("http://webService/", "TransitoWebPort"), TransitoWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransitoWeb
     */
    @WebEndpoint(name = "TransitoWebPort")
    public TransitoWeb getTransitoWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "TransitoWebPort"), TransitoWeb.class, features);
    }

}
