
package webService.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransitoWebService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8080/transito?wsdl")
public class TransitoWebService
    extends Service
{

    private final static URL TRANSITOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSITOWEBSERVICE_EXCEPTION;
    private final static QName TRANSITOWEBSERVICE_QNAME = new QName("http://webService/", "TransitoWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/transito?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSITOWEBSERVICE_WSDL_LOCATION = url;
        TRANSITOWEBSERVICE_EXCEPTION = e;
    }

    public TransitoWebService() {
        super(__getWsdlLocation(), TRANSITOWEBSERVICE_QNAME);
    }

    public TransitoWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSITOWEBSERVICE_QNAME, features);
    }

    public TransitoWebService(URL wsdlLocation) {
        super(wsdlLocation, TRANSITOWEBSERVICE_QNAME);
    }

    public TransitoWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSITOWEBSERVICE_QNAME, features);
    }

    public TransitoWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransitoWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransitoWeb
     */
    @WebEndpoint(name = "TransitoWebPort")
    public TransitoWeb getTransitoWebPort() {
        return super.getPort(new QName("http://webService/", "TransitoWebPort"), TransitoWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransitoWeb
     */
    @WebEndpoint(name = "TransitoWebPort")
    public TransitoWeb getTransitoWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "TransitoWebPort"), TransitoWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSITOWEBSERVICE_EXCEPTION!= null) {
            throw TRANSITOWEBSERVICE_EXCEPTION;
        }
        return TRANSITOWEBSERVICE_WSDL_LOCATION;
    }

}
