
package webService.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TransitoWeb", targetNamespace = "http://webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransitoWeb {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "connectVia", targetNamespace = "http://webService/", className = "webService.cliente.ConnectVia")
    @ResponseWrapper(localName = "connectViaResponse", targetNamespace = "http://webService/", className = "webService.cliente.ConnectViaResponse")
    public void connectVia(
        @WebParam(name = "arg0", targetNamespace = "")
        Via arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CanOpen")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CanOpen", targetNamespace = "http://webService/", className = "webService.cliente.CanOpen")
    @ResponseWrapper(localName = "CanOpenResponse", targetNamespace = "http://webService/", className = "webService.cliente.CanOpenResponse")
    public boolean canOpen(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webService.cliente.Via>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVias", targetNamespace = "http://webService/", className = "webService.cliente.GetVias")
    @ResponseWrapper(localName = "getViasResponse", targetNamespace = "http://webService/", className = "webService.cliente.GetViasResponse")
    public List<Via> getVias();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "connectSemaforo", targetNamespace = "http://webService/", className = "webService.cliente.ConnectSemaforo")
    @ResponseWrapper(localName = "connectSemaforoResponse", targetNamespace = "http://webService/", className = "webService.cliente.ConnectSemaforoResponse")
    public void connectSemaforo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
