
package webService.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VeiculoWebService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8080/veiculo?wsdl")
public class VeiculoWebService
    extends Service
{

    private final static URL VEICULOWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webService.cliente.VeiculoWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webService.cliente.VeiculoWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/veiculo?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/veiculo?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VEICULOWEBSERVICE_WSDL_LOCATION = url;
    }

    public VeiculoWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VeiculoWebService() {
        super(VEICULOWEBSERVICE_WSDL_LOCATION, new QName("http://webService/", "VeiculoWebService"));
    }

    /**
     * 
     * @return
     *     returns VeiculoWeb
     */
    @WebEndpoint(name = "VeiculoWebPort")
    public VeiculoWeb getVeiculoWebPort() {
        return super.getPort(new QName("http://webService/", "VeiculoWebPort"), VeiculoWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VeiculoWeb
     */
    @WebEndpoint(name = "VeiculoWebPort")
    public VeiculoWeb getVeiculoWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "VeiculoWebPort"), VeiculoWeb.class, features);
    }

}
