package BoasVindas;


/**
* BoasVindas/Msg_Boas_VindasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoasVindas.idl
* Quarta-feira, 26 de Junho de 2013 06h45min50s BRT
*/

public interface Msg_Boas_VindasOperations 
{
  String boas_vindas ();
} // interface Msg_Boas_VindasOperations
