package BoasVindas;


/**
* BoasVindas/Msg_Boas_Vindas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoasVindas.idl
* Quarta-feira, 26 de Junho de 2013 06h45min50s BRT
*/

public interface Msg_Boas_Vindas extends Msg_Boas_VindasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Msg_Boas_Vindas
