package generatedCorba;


/**
* generatedCorba/EstacionamentoController.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EstacionamentoController.idl
* Quarta-feira, 29 de Maio de 2013 18h59min23s AMT
*/

public interface EstacionamentoController extends EstacionamentoControllerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EstacionamentoController
