package generatedCorba;


/**
* generatedCorba/EstacionamentoControllerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EstacionamentoController.idl
* Quarta-feira, 29 de Maio de 2013 18h59min23s AMT
*/

public interface EstacionamentoControllerOperations 
{
  boolean reservaEstacionamento (String placa, org.omg.CORBA.BooleanHolder ret);
  boolean removeReserva (String placa, org.omg.CORBA.BooleanHolder ret);
  boolean isLotado (org.omg.CORBA.BooleanHolder ret);
} // interface EstacionamentoControllerOperations
