package generatedCorba;

/**
* generatedCorba/EstacionamentoControllerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EstacionamentoController.idl
* Quarta-feira, 29 de Maio de 2013 18h59min23s AMT
*/

public final class EstacionamentoControllerHolder implements org.omg.CORBA.portable.Streamable
{
  public generatedCorba.EstacionamentoController value = null;

  public EstacionamentoControllerHolder ()
  {
  }

  public EstacionamentoControllerHolder (generatedCorba.EstacionamentoController initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = generatedCorba.EstacionamentoControllerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    generatedCorba.EstacionamentoControllerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return generatedCorba.EstacionamentoControllerHelper.type ();
  }

}
